apiVersion: apps/v1
kind: Deployment # Deployment object
metadata:
  name: worker-deployment # Name of the deployment
spec: # Deployment configuration
  replicas: 1 # Number of replicas (pods) of this deployment
  selector:
    matchLabels:
      component: worker # set of pods this deployment is going to control
  template: # Pod template
    metadata:
      labels:
        component: worker # Deployment will use component to identify which pods it has to manage. Pod's label
    spec: # Specify all the different containers which are going to run inside this pod
      containers:
        - name: worker # Name of the container
          image: singhabhinav/factorial-project-worker-k8s:dev # Image using which the container will be created
          env: # These environment variables will be passed to container when it will be created inside the pod
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"